services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "uvicorn bot:fastapi_app --host 0.0.0.0 --port 10000"
    envVars:
      - key: BOT_TOKEN
        value: 7675768972:AAHoFsvoC3wwl3-iOyECHdNXrOpl6_ZiB7k
      - key: WEBHOOK_URL
        value: https://atomic96.onrender.com
